# Generated by Django 4.2.5 on 2023-09-10 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="This is the timestamp of the object creation.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="This is the timestamp of the object update",
                        verbose_name="updated at",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
            ],
            options={
                "verbose_name": "City",
                "verbose_name_plural": "Cities",
                "db_table": "samam_city",
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="This is the timestamp of the object creation.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="This is the timestamp of the object update",
                        verbose_name="updated at",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
                "db_table": "samam_country",
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300, unique=True)),
                ("language", models.CharField(max_length=5, unique=True)),
                (
                    "customer",
                    models.ForeignKey(
                        limit_choices_to={"is_customer": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "db_table": "palace_organization",
            },
        ),
        migrations.CreateModel(
            name="Palace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="This is the timestamp of the object creation.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="This is the timestamp of the object update",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Designates if this object should be considered active or not or to simulate soft delete behaviour.",
                        verbose_name="active",
                    ),
                ),
                ("banner", models.ImageField(blank=True, upload_to="palace/banner")),
                ("logo", models.ImageField(blank=True, upload_to="palace/logo")),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("address", models.CharField(max_length=255, verbose_name="address")),
                (
                    "is_private",
                    models.BooleanField(default=True, verbose_name="is private"),
                ),
                ("upstream_organization_code", models.IntegerField(blank=True)),
                ("land_area", models.IntegerField(verbose_name="land area")),
                ("noble_area", models.IntegerField(verbose_name="area of noble")),
                ("distance_to_province", models.IntegerField(blank=True)),
                ("distance_to_same_palace", models.IntegerField(blank=True)),
                ("operation_date", models.DateField(verbose_name="operation date")),
                (
                    "completion_certificate",
                    models.ImageField(upload_to="palace/completion_certificate"),
                ),
                ("completion_date", models.DateField(verbose_name="completion date")),
                ("ownership_code", models.IntegerField(blank=True)),
                (
                    "operation_license",
                    models.ImageField(
                        upload_to="palace/operation_license",
                        verbose_name="operation license",
                    ),
                ),
                ("phone", models.CharField(max_length=15, verbose_name="phone")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="palace email"),
                ),
                (
                    "website",
                    models.URLField(blank=True, max_length=300, verbose_name="website"),
                ),
                (
                    "postal_code",
                    models.CharField(max_length=15, verbose_name="postal code"),
                ),
                ("description", models.TextField()),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
            ],
            options={
                "verbose_name": "Palace",
                "verbose_name_plural": "Palaces",
                "db_table": "palace",
            },
        ),
        migrations.CreateModel(
            name="Province",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="This is the timestamp of the object creation.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="This is the timestamp of the object update",
                        verbose_name="updated at",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="palace.country",
                        verbose_name="country",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="palace.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Province",
                "verbose_name_plural": "Provinces",
                "db_table": "samam_province",
            },
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="name")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="palace.organization",
                    ),
                ),
                (
                    "palace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="palace.palace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Place",
                "verbose_name_plural": "Place",
                "db_table": "place",
            },
        ),
        migrations.CreateModel(
            name="PalaceKind",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="name")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="palace.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Palace Kind",
                "verbose_name_plural": "Palace Kinds",
                "db_table": "palace_kind",
            },
        ),
        migrations.CreateModel(
            name="PalaceAccountType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="name")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="palace.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Palace Account Type",
                "verbose_name_plural": "Palace Account Types",
                "db_table": "palace_account_type",
            },
        ),
        migrations.AddField(
            model_name="palace",
            name="account_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="palace.palaceaccounttype",
            ),
        ),
        migrations.AddField(
            model_name="palace",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="palace.city",
                verbose_name="city",
            ),
        ),
        migrations.AddField(
            model_name="palace",
            name="kind",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="palace.palacekind",
                verbose_name="kind",
            ),
        ),
        migrations.AddField(
            model_name="palace",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="palace.organization",
            ),
        ),
        migrations.AddField(
            model_name="palace",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="palace.palace",
                verbose_name="parent",
            ),
        ),
        migrations.CreateModel(
            name="LanguageCaption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="This is the timestamp of the object creation.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="This is the timestamp of the object update",
                        verbose_name="updated at",
                    ),
                ),
                ("title", models.TextField(verbose_name="title")),
                ("code", models.IntegerField(verbose_name="code")),
                (
                    "is_editable",
                    models.BooleanField(default=False, verbose_name="is editable"),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="palace.organization",
                        to_field="language",
                        verbose_name="language",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="palace.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Language Caption",
                "verbose_name_plural": "Language Captions",
                "db_table": "samam_language_caption",
            },
        ),
        migrations.CreateModel(
            name="DepartmentPhone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "phone_number",
                    models.CharField(max_length=15, verbose_name="palace phone"),
                ),
                (
                    "is_internal",
                    models.BooleanField(
                        default=False, verbose_name="is internal phone"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="palace.organization",
                    ),
                ),
                (
                    "palace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="palace.palace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Palace Phone",
                "verbose_name_plural": "Palace Phones",
                "db_table": "palace_phone",
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="This is the timestamp of the object creation.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="This is the timestamp of the object update",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Designates if this object should be considered active or not or to simulate soft delete behaviour.",
                        verbose_name="active",
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=400, verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "is_private",
                    models.BooleanField(default=False, verbose_name="is private"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                ("land_area", models.IntegerField(verbose_name="land area")),
                ("noble_area", models.IntegerField(verbose_name="area of noble")),
                ("operation_date", models.DateField(verbose_name="operation date")),
                ("completion_date", models.DateField(verbose_name="completion date")),
                (
                    "completion_certificate",
                    models.ImageField(upload_to="palace/completion_certificate"),
                ),
                (
                    "website",
                    models.URLField(blank=True, max_length=300, verbose_name="website"),
                ),
                (
                    "postal_code",
                    models.CharField(max_length=15, verbose_name="postal code"),
                ),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="palace.organization",
                    ),
                ),
                (
                    "palace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="palace.palace",
                    ),
                ),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="palace.department",
                        verbose_name="parent",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="palace.place",
                        verbose_name="place",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "db_table": "palace_department",
            },
        ),
        migrations.AddField(
            model_name="country",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="palace.organization",
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="palace.organization",
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="province",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="palace.province",
                verbose_name="province",
            ),
        ),
    ]
