# Generated by Django 4.2.5 on 2023-09-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("palace", "0002_alter_department_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="palace",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
