# Generated by Django 4.2.5 on 2023-09-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("palace", "0003_alter_palace_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="palace",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="palace",
            name="distance_to_province",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="palace",
            name="distance_to_same_palace",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="palace",
            name="land_area",
            field=models.IntegerField(null=True, verbose_name="land area"),
        ),
        migrations.AlterField(
            model_name="palace",
            name="noble_area",
            field=models.IntegerField(null=True, verbose_name="area of noble"),
        ),
        migrations.AlterField(
            model_name="palace",
            name="ownership_code",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="palace",
            name="upstream_organization_code",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
