# Generated by Django 4.2.5 on 2023-09-13 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import modules.domain.models.user
import mptt.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="last name"
                    ),
                ),
                (
                    "phone",
                    models.CharField(max_length=15, unique=True, verbose_name="phone"),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Designates if this user's email has been verified.",
                        verbose_name="email verified",
                    ),
                ),
                (
                    "is_customer",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user is customer or not",
                        verbose_name="is customer",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "db_table": "samam_user",
                "ordering": ["-date_joined"],
            },
            managers=[
                ("objects", modules.domain.models.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="This is the timestamp of the object creation.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="This is the timestamp of the object update",
                        verbose_name="updated at",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
            ],
            options={
                "verbose_name": "City",
                "verbose_name_plural": "Cities",
                "db_table": "samam_city",
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="This is the timestamp of the object creation.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="This is the timestamp of the object update",
                        verbose_name="updated at",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
                "db_table": "samam_country",
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300, verbose_name="name")),
                ("language", models.CharField(max_length=5, verbose_name="language")),
                (
                    "customer",
                    models.ForeignKey(
                        limit_choices_to={"is_customer": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "db_table": "samam_organization",
            },
        ),
        migrations.CreateModel(
            name="Palace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="This is the timestamp of the object creation.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="This is the timestamp of the object update",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Designates if this object should be considered active or not or to simulate soft delete behaviour.",
                        verbose_name="active",
                    ),
                ),
                ("banner", models.ImageField(blank=True, upload_to="palace/banner")),
                ("logo", models.ImageField(blank=True, upload_to="palace/logo")),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("address", models.CharField(max_length=255, verbose_name="address")),
                (
                    "is_private",
                    models.BooleanField(default=True, verbose_name="is private"),
                ),
                (
                    "upstream_organization_code",
                    models.IntegerField(blank=True, null=True),
                ),
                ("land_area", models.IntegerField(null=True, verbose_name="land area")),
                (
                    "noble_area",
                    models.IntegerField(null=True, verbose_name="area of noble"),
                ),
                ("distance_to_province", models.IntegerField(blank=True, null=True)),
                ("distance_to_same_palace", models.IntegerField(blank=True, null=True)),
                ("operation_date", models.DateField(verbose_name="operation date")),
                (
                    "completion_certificate",
                    models.ImageField(upload_to="palace/completion_certificate"),
                ),
                ("completion_date", models.DateField(verbose_name="completion date")),
                ("ownership_code", models.IntegerField(blank=True, null=True)),
                (
                    "operation_license",
                    models.ImageField(
                        upload_to="palace/operation_license",
                        verbose_name="operation license",
                    ),
                ),
                ("phone", models.CharField(max_length=15, verbose_name="phone")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="palace email"),
                ),
                (
                    "website",
                    models.URLField(blank=True, max_length=300, verbose_name="website"),
                ),
                (
                    "postal_code",
                    models.CharField(max_length=15, verbose_name="postal code"),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
            ],
            options={
                "verbose_name": "Palace",
                "verbose_name_plural": "Palaces",
                "db_table": "samam_palace",
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="This is the timestamp of the object creation.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="This is the timestamp of the object update",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Designates if this object should be considered active or not or to simulate soft delete behaviour.",
                        verbose_name="active",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="domain.organization",
                    ),
                ),
                (
                    "palace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="domain.palace",
                    ),
                ),
            ],
            options={
                "verbose_name": "team",
                "verbose_name_plural": "teams",
                "db_table": "samam_team",
            },
        ),
        migrations.CreateModel(
            name="TeamMembers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="domain.organization",
                    ),
                ),
                (
                    "palace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="domain.palace",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="domain.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "team member",
                "verbose_name_plural": "team members",
                "db_table": "samam_team_member",
            },
        ),
        migrations.CreateModel(
            name="Province",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="This is the timestamp of the object creation.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="This is the timestamp of the object update",
                        verbose_name="updated at",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="domain.country",
                        verbose_name="country",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="domain.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Province",
                "verbose_name_plural": "Provinces",
                "db_table": "samam_province",
            },
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="name")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="domain.organization",
                    ),
                ),
                (
                    "palace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="domain.palace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Place",
                "verbose_name_plural": "Place",
                "db_table": "samam_place",
            },
        ),
        migrations.CreateModel(
            name="PalaceKind",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="name")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="domain.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Palace Kind",
                "verbose_name_plural": "Palace Kinds",
                "db_table": "samam_palace_kind",
            },
        ),
        migrations.CreateModel(
            name="PalaceAccountType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="name")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="domain.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Palace Account Type",
                "verbose_name_plural": "Palace Account Types",
                "db_table": "samam_palace_account_type",
            },
        ),
        migrations.AddField(
            model_name="palace",
            name="account_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="domain.palaceaccounttype",
            ),
        ),
        migrations.AddField(
            model_name="palace",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="domain.city",
                verbose_name="city",
            ),
        ),
        migrations.AddField(
            model_name="palace",
            name="kind",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="domain.palacekind",
                verbose_name="kind",
            ),
        ),
        migrations.AddField(
            model_name="palace",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="domain.organization",
            ),
        ),
        migrations.AddField(
            model_name="palace",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="domain.palace",
                verbose_name="parent",
            ),
        ),
        migrations.CreateModel(
            name="LanguageCaption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="This is the timestamp of the object creation.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="This is the timestamp of the object update",
                        verbose_name="updated at",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("language", models.CharField(max_length=5, verbose_name="language")),
                ("code", models.IntegerField(verbose_name="code")),
                (
                    "is_editable",
                    models.BooleanField(default=False, verbose_name="is editable"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="domain.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Language Caption",
                "verbose_name_plural": "Language Captions",
                "db_table": "samam_language_caption",
            },
        ),
        migrations.CreateModel(
            name="DepartmentPhone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "phone_number",
                    models.CharField(max_length=15, verbose_name="palace phone"),
                ),
                (
                    "is_internal",
                    models.BooleanField(
                        default=False, verbose_name="is internal phone"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="domain.organization",
                    ),
                ),
                (
                    "palace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="domain.palace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Palace Phone",
                "verbose_name_plural": "Palace Phones",
                "db_table": "samam_palace_phone",
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="This is the timestamp of the object creation.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="This is the timestamp of the object update",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Designates if this object should be considered active or not or to simulate soft delete behaviour.",
                        verbose_name="active",
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "name",
                    models.CharField(blank=True, max_length=400, verbose_name="name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "is_private",
                    models.BooleanField(default=False, verbose_name="is private"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                ("land_area", models.IntegerField(verbose_name="land area")),
                ("noble_area", models.IntegerField(verbose_name="area of noble")),
                ("operation_date", models.DateField(verbose_name="operation date")),
                ("completion_date", models.DateField(verbose_name="completion date")),
                (
                    "completion_certificate",
                    models.ImageField(upload_to="palace/completion_certificate"),
                ),
                (
                    "website",
                    models.URLField(blank=True, max_length=300, verbose_name="website"),
                ),
                (
                    "postal_code",
                    models.CharField(max_length=15, verbose_name="postal code"),
                ),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="domain.organization",
                    ),
                ),
                (
                    "palace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="domain.palace",
                    ),
                ),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="domain.department",
                        verbose_name="parent",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="domain.place",
                        verbose_name="place",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "db_table": "samam_palace_department",
            },
        ),
        migrations.AddField(
            model_name="country",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="domain.organization",
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="domain.organization",
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="province",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="domain.province",
                verbose_name="province",
            ),
        ),
    ]
