# Generated by Django 4.2.5 on 2023-09-21 13:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("domain", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teamdistribution",
            options={
                "verbose_name": "Team Distribution",
                "verbose_name_plural": "Team Distributions",
            },
        ),
        migrations.AlterModelTable(
            name="palacestatushistory",
            table="samam_palace_status_history",
        ),
    ]
