# Generated by Django 4.2.5 on 2023-10-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domain", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="is_committee",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="place",
            name="is_equipment_location",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="place",
            name="is_management_leadership",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="place",
            name="is_team",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="place",
            name="is_workplace",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
