# Generated by Django 4.2.5 on 2023-11-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domain", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Supervisor",
            new_name="PalaceSupervisor",
        ),
        migrations.AddField(
            model_name="profile",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "occupied"),
                    (2, "earned leave"),
                    (3, "medical leave"),
                    (4, "academic leave"),
                    (5, "disability leave"),
                    (6, "unpaid leave"),
                    (7, "excused absence"),
                    (8, "unexcused absence"),
                    (9, "retirement"),
                    (10, "resignation"),
                    (11, "death"),
                    (12, "partial disability"),
                    (13, "general lethargy"),
                    (14, "on mission"),
                    (15, "academic mission"),
                    (16, "women part time"),
                    (17, "Participants in the coefficient workforce plan"),
                    (18, "Partially disabled due to work"),
                    (19, "Partial failure not caused by work"),
                    (20, "Work-related total disability"),
                    (21, "Non-work related total disability"),
                ],
                db_index=True,
                default=100,
            ),
            preserve_default=False,
        ),
    ]
