# Generated by Django 4.2.5 on 2023-09-20 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("domain", "0002_alter_user_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="PalaceStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start",
                    models.DateTimeField(auto_now_add=True, verbose_name="start at"),
                ),
                ("end", models.DateTimeField(verbose_name="end at")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="domain.organization",
                    ),
                ),
                (
                    "palace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="domain.palace",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="domain.palacestatus",
                        verbose_name="palace status history",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TeamDistribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "samam_palace_team_distribution",
            },
        ),
        migrations.RemoveField(
            model_name="teammembers",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="teammembers",
            name="palace",
        ),
        migrations.RemoveField(
            model_name="teammembers",
            name="team",
        ),
        migrations.RemoveField(
            model_name="teammembers",
            name="user",
        ),
        migrations.RemoveField(
            model_name="department",
            name="is_removed",
        ),
        migrations.DeleteModel(
            name="Team",
        ),
        migrations.DeleteModel(
            name="TeamMembers",
        ),
        migrations.AddField(
            model_name="teamdistribution",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="domain.department",
                verbose_name="department",
            ),
        ),
        migrations.AddField(
            model_name="teamdistribution",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="domain.organization",
            ),
        ),
        migrations.AddField(
            model_name="teamdistribution",
            name="palace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="domain.palace",
            ),
        ),
    ]
