# Generated by Django 4.2.5 on 2023-10-03 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("domain", "0002_alter_place_is_committee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationgraph",
            name="communicator",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
