# Generated by Django 4.2.5 on 2023-10-12 17:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("domain", "0003_organizationgraph_communicator"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "Profile", "verbose_name_plural": "Profiles"},
        ),
        migrations.AlterModelTable(
            name="profile",
            table="samam_profile",
        ),
    ]
