# Generated by Django 4.2.5 on 2023-09-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domain", "0003_palacestatushistory_teamdistribution_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="palace",
            name="completion_certificate",
            field=models.ImageField(
                blank=True, upload_to="palace/completion_certificate"
            ),
        ),
        migrations.AlterField(
            model_name="palace",
            name="completion_date",
            field=models.DateField(blank=True, verbose_name="completion date"),
        ),
        migrations.AlterField(
            model_name="palace",
            name="operation_license",
            field=models.ImageField(
                blank=True,
                upload_to="palace/operation_license",
                verbose_name="operation license",
            ),
        ),
    ]
