# Generated by Django 4.2.5 on 2023-09-20 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("domain", "0004_alter_palace_completion_certificate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="completion_certificate",
            field=models.ImageField(
                blank=True, null=True, upload_to="palace/completion_certificate"
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="completion_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="completion date"
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="land_area",
            field=models.IntegerField(blank=True, null=True, verbose_name="land area"),
        ),
        migrations.AlterField(
            model_name="department",
            name="noble_area",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="area of noble"
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="operation_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="operation date"
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="ownership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="domain.departmentownershiptype",
                verbose_name="department ownership type",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="domain.departmentstatus",
                verbose_name="department status",
            ),
        ),
    ]
