# Generated by Django 4.2.5 on 2023-10-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domain", "0004_alter_profile_options_alter_profile_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="is_main",
            field=models.BooleanField(default=False, verbose_name="is main job"),
        ),
    ]
